### ISSUE TITLE
Replace all usages of onTouchTap with onClick

### ISSUE THREAD

**Issue by jgreubel** [lo-tp/material-ui-pagination#16]
Hey again,

Material-UI just removed their dependency on `onTouchTap` in their most recent version **0.19.0**.  And if I update to that version, this pagination component still uses it and throws an exception whenever I click on any button in this component.  To fix this, simply replace all usages of `onTouchTap` with `onClick`.  

Link to their release notes: https://github.com/callemall/material-ui/releases/tag/v0.19.0

**Comment by lo-tp** [comment]
@jgreubel 
Hey, I've upload a new version at [removeTap](https://github.com/lo-tp/material-ui-pagination/tree/removeTap)
Could you please try and see if it works?

**Comment by jgreubel** [comment]
Hey, after trying a few ways to test this, I believe your changes on the `removeTap` branch did fix the issue.  There may be a warning in the console still, but that may just be by the way I was testing it.

The ideal way I was trying to test this was having my package.json point to your branch, like so: `npm install material-ui-pagination@git://github.com/to-lp/material-ui-pagination.git#removeTap`.  However, with this approach, nothing is in the `dist` folder and therefor any imports I have don't work.  In hind sight, I should of just moved the index.jsx from the `src` folder into the `dist` folder.

The second way I tested this was to stay on my current version of this package and simply edit the index.js in the `dist` folder with the code changes you made on the `removeTap` branch.  This way made the page render and work again, however there was a warning still in my browser's console when testing.  I'm hoping this is because of the weird way I was testing this.  

I say go for the release and if there's a warning, we figure it out and make another release?

**Comment by lo-tp** [comment]
Ok. I published the `removeTap` version to npm at **next** tag.
Now you can install by `npm install material-ui-pagination@next`.
I'll update the readme later.
I'll giver the **latest** tag to this version later.

**Comment by jgreubel** [comment]
I tested this by installing the `next` tag and it worked perfectly with no warnings in the console. Thank you for the quick responses!

-------
**UPDATE**:  @lo-tp Actually, the warning still persists, and causes my app to slow down on encountering it.  This is the stack trace I see when rendering a page with this pagination component on `v1.1.5`:

```
main-d5092958304333a0529a219b3fca4652.js:5148 Warning: Unknown prop `onTouchTap` on <button> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in button (created by EnhancedButton)
    in EnhancedButton (created by FlatButton)
    in FlatButton (created by k)
    in k (created by Pagination)
    in div (created by Pagination)
    in Pagination (created by Table)
    in div (created by Table)
    in td (created by TableRowColumn)
    in TableRowColumn (created by Table)
    in tr (created by TableRow)
    in TableRow (created by Table)
    in tfoot (created by TableFooter)
    in TableFooter (created by Table)
    in table (created by Table)
    in div (created by Table)
```

Somehow an onTouchTap is still on a button somewhere?  I'm going to look into issues on Material-UI's github to see if any are related.

**Comment by jgreubel** [comment]
Ahh I think I figured it out.  You need to update YOUR version of material-ui as well to `0.19.0` in your package.json.

I think you should put Material-UI in your package.json **NOT** as a direct dependency, but mark it as a **PeerDependency** so that it requires us to install it when using this package. This would prevent the weirdness of your Material-UI version being different from my Material-UI version. 

Docs: https://docs.npmjs.com/files/package.json#peerdependencies
Blog: https://nodejs.org/en/blog/npm/peer-dependencies/
Example: https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/package.json

**Comment by lo-tp** [comment]
@jgreubel 
Now in version `1.1.6` react, react-dom and material-ui  should be installed as peer dependencies.

**Comment by jgreubel** [comment]
@lo-tp I finally think this is working correctly.  I removed my node_modules and re-isntalled them before testing, and now I do not see that warning.  Thanks again for all the work.

**Comment by lo-tp** [comment]
Hi @jgreubel Actually the migration from dependencies to peer dependencies caused unit test failure because peer dependencies were not installed in dev and test environments.

To solve this problem, I'm considering adding `react, react-dom, material-ui` as both peer and dev dependencies.

Do you have any better idea?

**Comment by jgreubel** [comment]
It looks like the example I posted is doing that as well.  It seems like a decent idea.  Go for it, but maybe check the NPM docs if they have another solution.

**Comment by jgreubel** [comment]
I'm assuming you can close this if you want.  Version **1.1.6** has been working for me for the last 3 weeks.

**Comment by ilhambrata** [comment]
hi @jgreubel after I installed, why the material-ui-pagination@next still need the old one material-ui dependencies.

I see this warning `material-ui-pagination@1.1.7 requires a peer of material-ui@>= 0.19.0 < 1.0.0 but none is installed. You must install peer dependencies yourself.`

and the error ` /Users/retina/Documents/boss3/bossadmin/src/material-ui/svg-icons/navigation/last-page.js doesn't exist  as directory`

Thanks before.
